In [36]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
pre_csv = pd.read_csv('/Users/soyoung/ml_project/airplane/finaldata.csv')
test_csv = pd.read_csv('/Users/soyoung/ml_project/airplane/test.csv')
df_pre = pd.DataFrame(pre_csv)
df_test = pd.DataFrame(test_csv)

In [37]:
df_pre['date'] = df_pre['Month'].astype(str)+'-'+df_pre['Day_of_Month'].astype(str)
df_pre['date'] = pd.to_datetime(df_pre['date'], format='%m-%d')
df_test['date'] = df_test['Month'].astype(str)+'-'+df_test['Day_of_Month'].astype(str)
df_test['date'] = pd.to_datetime(df_test['date'], format='%m-%d')

In [38]:
encoder = LabelEncoder()
df2 = pd.DataFrame(columns=['ID','Not_Delayed','Delayed'])
df2['ID'] = df_test['ID']

list = ['ID','date','Origin_Airport','Origin_State','Destination_Airport','Destination_State','Airline','Carrier_Code(IATA)','Tail_Number']
for name in list:
    df_test[name] = encoder.fit_transform(df_test[name])
    df_pre[name] = encoder.fit_transform(df_pre[name])

list2 = ["Estimated_Departure_Time","Estimated_Arrival_Time","Origin_State","Destination_State","Airline","Carrier_Code(IATA)","Carrier_ID(DOT)"]
for name in list2:
    df_test[name].fillna(df_test[name].mode()[0],inplace=True)
    df_pre[name].fillna(df_pre[name].mode()[0],inplace=True)

# df_test["Estimated_Departure_Time"].fillna(df_test["Estimated_Departure_Time"].mode()[0],inplace=True)
# df_test["Estimated_Arrival_Time"].fillna(df_test["Estimated_Arrival_Time"].mode()[0],inplace=True)
# df_test["Origin_State"].fillna(df_test["Origin_State"].mode()[0],inplace=True)
# df_test["Destination_State"].fillna(df_test["Destination_State"].mode()[0],inplace=True)
# df_test["Airline"].fillna(df_test["Airline"].mode()[0],inplace=True)
# df_test["Carrier_Code(IATA)"].fillna(df_test["Carrier_Code(IATA)"].mode()[0],inplace=True)
# df_test["Carrier_ID(DOT)"].fillna(df_test["Carrier_ID(DOT)"].mode()[0],inplace=True)

In [39]:
X = df_pre.drop(['Delay'],axis=1)
y = df_pre['Delay']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [40]:
scaler = StandardScaler()
droplist = ['Delay','ID','Month', 'Day_of_Month','Cancelled','Origin_Airport_ID', 'Origin_State', 'Diverted','Destination_Airport_ID', 'Destination_State','Carrier_ID(DOT)']
droplist2 = ['ID','Month', 'Day_of_Month','Cancelled','Origin_Airport_ID', 'Origin_State', 'Diverted','Destination_Airport_ID', 'Destination_State','Carrier_ID(DOT)']
X = df_pre.drop(droplist,axis=1)
y = df_pre['Delay']
scaler.fit(X)
scaler.transform(X)
X2 = df_test.drop(droplist2,axis=1)
scaler.fit(X2)
scaler.transform(X2)

array([[-0.2623209 ,  0.97126485, -0.1393173 , ...,  0.64183853,
         0.638707  ,  1.52138516],
       [ 0.39912164,  0.24509786, -0.63677763, ..., -0.80848415,
        -0.7086865 ,  0.62938603],
       [ 0.59140144,  0.62232747,  0.72626368, ...,  0.64183853,
        -0.59100069, -1.15461223],
       ...,
       [ 0.80290923,  0.60723828, -0.15921571, ...,  0.64183853,
        -0.33111121, -0.24383417],
       [-1.33139662, -2.04657199,  1.26352084, ..., -0.96963111,
         1.70932091,  1.24909069],
       [-0.13926182, -0.45277691,  0.64667003, ...,  0.96413246,
         0.37554846,  0.92045943]])

In [41]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

In [42]:
X = df_pre.drop(['Delay'],axis=1)
y = df_pre['Delay']
X

,ID,Month,Day_of_Month,Estimated_Departure_Time,Estimated_Arrival_Time,Cancelled,Diverted,Origin_Airport,Origin_Airport_ID,Origin_State,Destination_Airport,Destination_Airport_ID,Destination_State,Distance,Airline,Carrier_Code(IATA),Carrier_ID(DOT),Tail_Number,date
0,5,4,13,1545.0,1900.0,0,0,119,11618,52,93,11278,47,199.0,21,8,20452.0,3435,102
1,6,1,20,1742.0,1903.0,0,0,119,11618,28,47,10721,19,200.0,26,8,19393.0,3495,19
2,8,6,13,1420.0,1550.0,0,0,59,10821,52,74,11057,31,361.0,23,10,19393.0,4083,163
3,10,8,13,1730.0,1844.0,0,0,93,11278,47,277,14122,36,204.0,21,0,19393.0,241,224
4,12,1,12,1015.0,1145.0,0,0,72,11042,33,94,11292,5,1201.0,23,10,19393.0,5171,11
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,999995,9,18,936.0,1243.0,0,0,256,13930,52,270,14100,52,678.0,26,8,19977.0,2477,260
999996,999996,5,30,920.0,1028.0,0,0,122,11637,52,242,13487,21,223.0,22,3,19393.0,2294,149
999997,999997,6,28,800.0,1340.0,0,0,248,13796,52,159,12191,42,1642.0,23,10,19393.0,994,178
999998,999998,9,27,1613.0,1824.0,0,0,45,10693,41,22,10397,52,214.0,9,3,19790.0,6207,269
999999,999999,3,26,1800.0,2056.0,0,0,307,14635,7,103,11433,20,1084.0,28,3,19790.0,3667,84

In [43]:
X_train,X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)

In [44]:
rf_clf = RandomForestClassifier(random_state=221)
rf_clf.fit(X_train, y_train)
pred = rf_clf.predict(X_test)
accuracy = accuracy_score(y_test, pred)
print('랜덤 포레스트 정확도: {:.4f}'.format(accuracy))

랜덤 포레스트 정확도: 0.9546

In [45]:
X2 = df_test
pred2 = rf_clf.predict_proba(X2)

In [46]:
final = pd.DataFrame(pred2,columns=['not','del'])
df2['Not_Delayed'] = final['not']
df2['Delayed'] = final['del']

In [47]:
df2.to_csv('final2.csv',encoding='utf-8',index=False)